# CircleCI configuration file
version: 2.1
jobs:
  build:
    working_directory: ~/android-boilerplate
    docker:
      - image: circleci/android:api-29
    environment:
      GRADLE_OPTS: -Xmx4g -Dorg.gradle.daemon=false
      JVM_OPTS: -Xmx4g
    steps:
      - checkout
      - run: echo "RELEASE.KEY_ALIAS=$SIGNING_KEY_ALIAS" >> keystore.properties
      - run: echo "RELEASE.KEY_PASSWORD=$SIGNING_KEY_PASSWORD" >> keystore.properties
      - run: echo "RELEASE.STORE_FILE=$SIGNING_STORE_FILE" >> keystore.properties
      - run: echo "RELEASE.STORE_PASSWORD=$SIGNING_STORE_PASSWORD" >> keystore.properties
      - restore_cache:
          key: gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - run:
          name: Run Ktlint
          command: ./gradlew ktlint
      - run:
          name: Run Lint
          command: ./gradlew lintDevDebug
      - run:
          name: Run Spotless
          command: ./gradlew spotlessCheck
      - run:
          name: Run Unit Tests
          command: ./gradlew testDevDebugUnitTest
      - store_artifacts:
          path: build/dependencyUpdates
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
