name: Production Release

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run unit tests & static analysis checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11

        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Unit Tests
        run: ./gradlew testDevDebug

      - name: Run Static Analysis Checks
        run: ./gradlew detekt ktlint lintDevDebug spotlessCheck --daemon

  buildAndDeployAPK:
    name: Build signed APK and deploy to AppCenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11

        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Add keystore properties
        env:
          KEYSTORE_PROPERTIES_BASE64: ${{ secrets.KEYSTORE_PROPERTIES_BASE64 }}
        run: base64 -d <<< $KEYSTORE_PROPERTIES_BASE64 > keystore.properties

      - name: Add keystore file
        env:
          MOVEE_KEYSTORE_BASE64: ${{ secrets.MOVEE_KEYSTORE_BASE64 }}
        run: base64 -d <<< $MOVEE_KEYSTORE_BASE64 > movee.keystore

      - name: Build APK
        run: |
          bash ./gradlew assemblePrdRelease
          mv $(ls app/build/outputs/apk/prd/release/*.apk) app-release.apk
      # TODO update above when AppCenter-Github-Action supports ant style glob pattern

      - name: Upload APK to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1.0.0
        with:
          appName: adesso-Turkey/Movee
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: adesso
          file: app-release.apk

  # TODO deploy to PlayStore:
  # TODO notifyTeams:
